---
apiVersion: v1
data:
  config.yaml: |-
    app:
      httpAddr: "localhost"
      httpPort: 9001
      name: "k8s-agent-go"
      key: "8e6847e3cb5b48cf216a1adf8f98bf5b"
      logger:
        level: "DEBUG"
        type: "text"
    checkSign: false
    grpc:
      serverAddr: 42.193.128.145:10000
      appName: 123123
      secret: '123123#'
      tsl:
        open: false
        hostname: "iadmin.sdm.qq.com"
        caPath: "/data/app/config/sdm.qq.com.pem"
      xxl:
        glueExecutorId: "2"
        baseurl: "http://127.0.0.1:1015/"
        token: "000"
kind: ConfigMap
metadata:
  name: k8s-agent-go
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: k8s-agent-go
    qcloud-app: k8s-agent-go
  name: k8s-agent-go
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: k8s-agent-go
      qcloud-app: k8s-agent-go
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: k8s-agent-go
        qcloud-app: k8s-agent-go
    spec:
      containers:
      - args:
        - --config=/data/config/config.yaml
        command:
        - /data/app/app-go
        env:
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        image: wuhan.tencentcloudcr.com/tsmbu-prd/k8s-agent-go:v1.0.11_feature-base_1c4135f9
        imagePullPolicy: IfNotPresent
        name: k8s-agent-go
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 256Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/config
          name: config
          readOnly: true
        workingDir: /data/app/
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: vpub
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: k8s-agent-go
        name: config
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    manager: tke-apiserver
  name: k8s-agent-go
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
---
